# Generated by Django 2.2.6 on 2019-10-27 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
