# Generated by Django 2.2.6 on 2019-10-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('complement', models.CharField(max_length=200, verbose_name='Complemento')),
                ('postal_code', models.CharField(max_length=20, verbose_name='CEP')),
                ('city', models.CharField(max_length=200, verbose_name='Cidade')),
                ('state', models.CharField(max_length=200, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
