# Generated by Django 2.2.6 on 2019-10-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
