# Generated by Django 2.2.6 on 2019-12-03 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20191027_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Quantidade')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(to='sales.InvoiceProduct', verbose_name='Produtos'),
        ),
    ]
