# Generated by Django 2.2.6 on 2019-12-03 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20191203_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Quantidade')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'ServiçoFatura',
                'verbose_name_plural': 'ServiçosFatura',
            },
        ),
        migrations.AlterModelOptions(
            name='invoiceproduct',
            options={'verbose_name': 'ProdutoFatura', 'verbose_name_plural': 'ProdutosFatura'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='services',
            field=models.ManyToManyField(to='sales.InvoiceService', verbose_name='Serviços'),
        ),
    ]
