# Generated by Django 2.2.6 on 2019-12-03 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20191027_0325'),
        ('sales', '0010_auto_20191203_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceproduct',
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos'
            },
        ),
        migrations.AlterModelOptions(
            name='invoiceservice',
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços'
            },
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='contacts.Client',
                verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
    ]
